# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eureka-deployment
serviceName: eureka
appLabel: eureka
appName: eureka

replicaCount: 1

image:
  repository: ichwansh34/eureka
  tag: v2

containerPort: 8083

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false