# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: ichwansh34/gatewayserver
  tag: v2

containerPort: 8084

service:
  type: LoadBalancer
  port: 8084
  targetPort: 8084

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false