apiVersion: apps/v1 #digunakan untuk resource deployment/StatefulSet/DaemonSet/ReplicaSet
kind: Deployment
metadata:
  name: employee-deployment
  labels:
    app: employee
spec:
  replicas: 1 #jumlah pod yang ingin dijalankan dan memastikan bahwa selalu ada 1 pod yg aktif
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: ichwansh34/employee:v2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: pos-configmap
                  key: EMPLOYEE_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: pos-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: pos-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  selector:
    app: employee
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080