apiVersion: apps/v1 #digunakan untuk resource deployment/StatefulSet/DaemonSet/ReplicaSet
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1 #jumlah pod yang ingin dijalankan dan memastikan bahwa selalu ada 1 pod yg aktif
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: ichwansh34/eureka:v2
        ports:
        - containerPort: 8083
        env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: pos-configmap
                key: EUREKA_APPLICATION_NAME
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: pos-configmap
                key: SPRING_CONFIG_IMPORT

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083